
def full_names():
    names = [
    ("Juan", "Martinez"), ("Maria", "Garcia"), ("Carlos", "Rodriguez"), ("Isabel", "Lopez"),
    ("Alejandro", "Hernandez"), ("Sofia", "Perez"), ("Eduardo", "Ramirez"), ("Ana", "Morales"),
    ("Luis", "Torres"), ("Rosa", "Sanchez"), ("Antonio", "Fernandez"), ("Lucia", "Chavez"),
    ("Jose", "Flores"), ("Carmen", "Gonzalez"), ("Miguel", "Vargas"), ("Laura", "Jimenez"),
    ("Roberto", "Diaz"), ("Patricia", "Ortega"), ("Diego", "Rios"), ("Mariana", "Silva"),
    ("Rajesh", "Kumar"), ("Priya", "Singh"), ("Arjun", "Patel"), ("Aishwarya", "Sharma"),
    ("Siddharth", "Gupta"), ("Sweta", "Verma"), ("Anand", "Mishra"), ("Nisha", "Reddy"),
    ("Rohit", "Choudhary"), ("Meera", "Yadav"), ("Ravi", "Tiwari"), ("Divya", "Nair"),
    ("Sanjay", "Dubey"), ("Pooja", "Mehta"), ("Vikram", "Rajan"), ("Kavita", "Agarwal"),
    ("Deepak", "Joshi"), ("Ayesha", "Khanna"), ("Vivek", "Rana"), ("Shreya", "Desai"),
    ("Jose", "Cruz"), ("Maria", "Santos"), ("Carlos", "Reyes"), ("Lorna", "Fernandez"),
    ("Eduardo", "Lim"), ("Rosa", "Gonzales"), ("Manuel", "Tan"), ("Anna", "Dela Cruz"),
    ("Antonio", "Garcia"), ("Sophia", "Lopez"), ("Diego", "Rivera"), ("Camille", "Torres"),
    ("Andrei", "Villanueva"), ("Bernadette", "Martinez"), ("Michael", "Sison"), ("Liza", "Pascual"),
    ("Victor", "Reyes"), ("Elena", "Ramos"), ("Andres", "Abad"), ("Carmina", "Bautista"),
    ("Wei", "Li"), ("Jing", "Zhang"), ("Tao", "Wang"), ("Mei", "Chen"), ("Jun", "Yang"),
    ("Ying", "Liu"), ("Xing", "Huang"), ("Liang", "Wu"), ("Hui", "Xu"), ("Ming", "Zhang"),
    ("Lei", "Wang"), ("Xin", "Zhao"), ("Fei", "Guo"), ("Jia", "Li"), ("Shu", "Mei"), ("Xiang", "Chen"),
    ("Yan", "Liu"), ("Minghui", "Xu"), ("Rui", "Wang"), ("Xiaojun", "Zhang"),
    ("Minh", "Nguyen"), ("Thuy", "Tran"), ("Tuan", "Pham"), ("Lan", "Le"), ("Dat", "Vo"),
    ("Linh", "Hoang"), ("Ngoc", "Ngo"), ("Cuong", "Bui"), ("Huong", "Dang"), ("Huy", "Nguyen"),
    ("Mai", "Do"), ("Quang", "Luu"), ("Kim", "Tran"), ("Thanh", "Ho"), ("Van", "Huynh"),
    ("Hien", "Ho"), ("Khoa", "Phan"), ("Ha", "Vu"), ("Quyen", "Truong"), ("Tien", "Ly"),
    ("Mehmet", "Yilmaz"), ("Ayse", "Kaya"), ("Emre", "Demir"), ("Zeynep", "Tekin"), ("Cem", "Aksoy"),
    ("Elif", "Ozdemir"), ("Serkan", "Erdogan"), ("Sevgi", "Cetin"), ("Burak", "Ozkan"), ("Yasmin", "Arslan"),
    ("Can", "Genc"), ("Nilay", "Cinar"), ("Ali", "Yavuz"), ("Derya", "Karatas"), ("Eren", "Aydin"),
    ("Melis", "Korkmaz"), ("Selim", "Demirtas"), ("Ceren", "Sahin"), ("Baran", "Yildirim"), ("Aslihan", "Tanrikulu"),
    ("Ivan", "Petrov"), ("Olga", "Ivanova"), ("Mikhail", "Smirnov"), ("Elena", "Kuznetsova"),
    ("Dmitry", "Sokolov"), ("Tatiana", "Volkova"), ("Sergei", "Morozov"), ("Anna", "Pavlova"),
    ("Andrei", "Sidorov"), ("Natalia", "Orlova"), ("Pavel", "Novikov"), ("Yulia", "Voronina"),
    ("Anton", "Kozlov"), ("Ekaterina", "Popova"), ("Alexei", "Belyakov"), ("Marina", "Fedorova"),
    ("Roman", "Egorov"), ("Daria", "Nikitina"), ("Nikita", "Voronov"), ("Larisa", "Sokolova"),
    ("Askarov", "Nurmat"), ("Aida", "Akmatova"), ("Azimov", "Muktar"), ("Gulnara", "Jumabekova"),
    ("Ruslanbek", "Tursunov"), ("Aizere", "Kadyrova"), ("Janybek", "Orozov"), ("Elmira", "Ismailova"),
    ("Temirbek", "Asanov"), ("Nazgul", "Mamatova"), ("Kurmanbek", "Jumabekov"), ("Gulmira", "Karimova"),
    ("Asylbek", "Abdyldaev"), ("Zhyldyz", "Mambetalieva"), ("Zamira", "Sadykova"), ("Tynchtyk", "Isakov"),
    ("Nikos", "Papadopoulos"), ("Maria", "Ioannou"), ("Yiannis", "Dimitriou"), ("Eleni", "Kostas"),
    ("Andreas", "Papadakis"), ("Sophia", "Georgiou"), ("Stavros", "Vasilopoulos"), ("Katerina", "Angelopoulos"),
    ("Panos", "Nikopoulos"), ("Despina", "Antoniou"), ("Dimitris", "Andreadis"), ("Athena", "Sotiriou"),
    ("Giorgos", "Katsaris"), ("Eirini", "Pappas"), ("Christos", "Zografos"), ("Eleftheria", "Arvanitis"),
    ("Pavlos", "Athanasiou"), ("Chrysa", "Papageorgiou"), ("Antonis", "Manolis"), ("Kalliope", "Papadopoulou"),
    ("Aino", "Virtanen"), ("Lauri", "Mäkinen"), ("Sofia", "Järvinen"), ("Eero", "Koivisto"),
    ("Aava", "Nieminen"), ("Onni", "Koskinen"), ("Ella", "Laine"), ("Matias", "Hämäläinen"),
    ("Iida", "Lehtonen"), ("Juho", "Vainio"), ("Siiri", "Korhonen"), ("Santeri", "Rautio"),
    ("Linnea", "Lappalainen"), ("Aleksi", "Ojala"), ("Anni", "Korpela"), ("Eetu", "Peltola"),
    ("Elina", "Kallio"), ("Tuomas", "Lahti"), ("Saara", "Ranta"), ("Otto", "Räsänen"),
    ("Jan", "de Vries"), ("Emma", "van der Berg"), ("Thijs", "van Dijk"), ("Lisa", "Jansen"),
    ("Daan", "Bakker"), ("Sophie", "Visser"), ("Bram", "de Boer"), ("Julia", "Smit"),
    ("Tim", "van Leeuwen"), ("Sarah", "Groen"), ("Martijn", "Willems"), ("Laura", "van Rijn"),
    ("Sander", "Hendriks"), ("Maud", "Vos"), ("Lars", "van Houten"), ("Floor", "van Gogh"),
    ("Jeroen", "de Koning"), ("Kim", "Vermeer"), ("Lucas", "van Dam"), ("Nina", "van Hoorn"),
    ("Avi", "Cohen"), ("Maya", "Levi"), ("Yair", "Ben-David"), ("Talia", "Rosenberg"),
    ("Amit", "Goldstein"), ("Noa", "Weiss"), ("Itay", "Mizrahi"), ("Shira", "Cohen"),
    ("Eitan", "Golan"), ("Roni", "Amir"), ("Liora", "Barak"), ("Uriel", "Dayan"),
    ("Michal", "Shalev"), ("Daniel", "Cohen"), ("Liat", "Abadi"), ("Omri", "Levi"),
    ("Shani", "Cohen"), ("Ariel", "Weitz"), ("Neta", "Yosef"), ("Yael", "Alon"),
    ("Hiroshi", "Tanaka"), ("Yuki", "Suzuki"), ("Takashi", "Nakamura"), ("Aiko", "Kobayashi"),
    ("Haruto", "Sato"), ("Riko", "Ito"), ("Kazuki", "Yamamoto"), ("Nao", "Sakurai"),
    ("Kaito", "Aoki"), ("Yui", "Suzuki"), ("Shota", "Watanabe"), ("Miki", "Ono"),
    ("Kenji", "Inoue"), ("Sora", "Yamada"), ("Hina", "Sasaki"), ("Ryo", "Taniguchi"),
    ("Yukiho", "Kato"), ("Shintaro", "Mori"), ("Aya", "Fujimoto"), ("Yuta", "Nakajima"),
    ("Min", "Joon"), ("Ji", "Eun"), ("Hyun", "Woo"), ("Soo", "Young"),
    ("Dong", "Hoon"), ("Ji", "Hye"), ("Ki", "Tae"), ("Mi", "Kyung"),
    ("Ji", "Hoon"), ("Min", "Hee"), ("Seok", "Jin"), ("Ji", "Yoon"),
    ("Joon", "Young"), ("Eun", "Mi"), ("Ki", "Young"), ("Soo", "Jin"),
    ("Ho", "Seok"), ("Ji", "Eun"), ("Sang", "Hyun"), ("Ji", "Won"),
    ("Carlos", "Perez"), ("Maria", "Rodriguez"), ("Juan", "Lopez"), ("Isabel", "Morales"),
    ("Diego", "Castillo"), ("Ana", "Garcia"), ("Luis", "Hernandez"), ("Sofia", "Chavez"),
    ("Pedro", "Reyes"), ("Laura", "Fernandez"), ("Alejandro", "Ramirez"), ("Lucia", "Torres"),
    ("Jorge", "Mendez"), ("Maria", "Gonzalez"), ("Daniel", "Morales"), ("Karen", "Lopez"),
    ("Manuel", "Soto"), ("Elena", "Vasquez"), ("Miguel", "Martinez"), ("Sandra", "Herrera"),
    ("Alejandro", "Rodriguez"), ("Maria", "Perez"), ("Juan", "Gonzalez"), ("Ana", "Martinez"),
    ("Carlos", "Hernandez"), ("Isabel", "Diaz"), ("Luis", "Ramirez"), ("Sofia", "Castro"),
    ("Miguel", "Lopez"), ("Rosa", "Suarez"), ("Antonio", "Fernandez"), ("Laura", "Morales"),
    ("Pedro", "Cruz"), ("Carmen", "Ortega"), ("Diego", "Jimenez"), ("Teresa", "Garcia"),
    ("Jose", "Gonzalez"), ("Marta", "Alvarez"), ("Manuel", "Vargas"), ("Ana", "Romero"),
    ("Somchai", "Suriyakorn"), ("Naree", "Thanaporn"), ("Thana", "Wongsawat"), ("Sirima", "Chan"),
    ("Somsak", "Prasert"), ("Pimjai", "Tanthai"), ("Wirat", "Chaisong"), ("Sirirat", "Chokdee"),
    ("Nopporn", "Kamsai"), ("Orathai", "Suksawat"), ("Nattapong", "Rattanakul"), ("Sujin", "Promthong"),
    ("Sirin", "Phongrak"), ("Nareerat", "Sripoom"), ("Thammarat", "Boonchu"), ("Araya", "Inthara"),
    ("Tanin", "Kongthong"), ("Wimonrat", "Khunthong"), ("Santisuk", "Charoenrat"), ("Somjai", "Rojanaphong"),
    ("Ahmed", "El Amrani"), ("Fatima", "Ben Salah"), ("Mohammed", "Lahcen"), ("Leila", "Belkadi"),
    ("Abdel", "Rahman Zeroual"), ("Amina", "Bouhaddou"), ("Rachid", "El Mansouri"), ("Hafsa", "Zerhouni"),
    ("Karim", "Moussa"), ("Khadija", "Azzouzi"), ("Samir", "Chakir"), ("Naima", "Benkirane"),
    ("Youssef", "El Fassi"), ("Salma", "Chafik"), ("Tarik", "El Khatib"), ("Aicha", "El Mernissi"),
    ("Anas", "Bensaid"), ("Loubna", "El Hachimi"), ("Abdellah", "Belhaj"), ("Amal", "Haddad"),
    ("João", "Silva"), ("Maria", "Dos Santos"), ("Manuel", "Pereira"), ("Ana", "Gomes"),
    ("Carlos", "Ferreira"), ("Isabel", "Almeida"), ("José", "Rodrigues"), ("Sofia", "Carvalho"),
    ("Pedro", "Fernandes"), ("Laura", "Machado"), ("António", "Lopes"), ("Mariana", "Correia"),
    ("Rui", "Santos"), ("Helena", "Martins"), ("Francisco", "Oliveira"), ("Clara", "Coelho"),
    ("Paulo", "Barbosa"), ("Rita", "Costa"), ("Joaquim", "Ramos"), ("Inês", "Sousa"),
    ("Rajesh", "Adhikari"), ("Sunita", "Thapa"), ("Binod", "Sharma"), ("Manisha", "Rai"),
    ("Dipak", "Shrestha"), ("Sita", "Joshi"), ("Ashok", "Gurung"), ("Nirmala", "Bhattarai"),
    ("Anil", "Tamang"), ("Sarita", "Dhungana"), ("Ramesh", "Koirala"), ("Bimala", "Lama"),
    ("Prakash", "Basnet"), ("Gita", "Magar"), ("Bikash", "Rana"), ("Kalpana", "Shah"),
    ("Shyam", "Rai"), ("Laxmi", "Poudel"), ("Deepak", "Khadka"), ("Rupa", "Gautam"),
    ("Dmitri", "Ivanov"), ("Yelena", "Petrova"), ("Mikhail", "Sidorov"), ("Anastasia", "Kozlova"),
    ("Ivan", "Smirnov"), ("Ekaterina", "Pavlova"), ("Alexander", "Popov"), ("Olga", "Sokolova"),
    ("Sergei", "Volkov"), ("Natalia", "Morozova"), ("Andrey", "Ivanov"), ("Yulia", "Kuznetsova"),
    ("Vladimir", "Petrov"), ("Svetlana", "Smirnova"), ("Igor", "Antonov"), ("Marina", "Kravchenko"),
    ("Pavel", "Fedorov"), ("Anna", "Voronina"), ("Denis", "Korolev"), ("Irina", "Belyakova"),
    ("Ahmed", "Abdel Rahman"), ("Nour", "Khalil"), ("Mohamed", "El-Amin"), ("Yasmin", "Ibrahim"),
    ("Tarek", "Samir"), ("Rania", "Mahmoud"), ("Amr", "Fawzi"), ("Dina", "Hassan"),
    ("Hossam", "Kamal"), ("Salma", "Khattab"), ("Khaled", "Ali"), ("Aya", "Hamza"),
    ("Hesham", "Mansour"), ("Shaimaa", "Rizk"), ("Sherif", "Zaki"), ("Laila", "Mostafa"),
    ("Tamer", "Wahba"), ("Eman", "Sayed"), ("Kareem", "Ezzat"), ("Rasha", "Saleh"),
    ("Ahmed", "Abdel Rahman"), ("Fatima", "Ali"), ("Mohamed", "Hassan"), ("Yasmin", "Osman"),
    ("El Tayeb", "Ibrahim"), ("Nada", "Mustafa"), ("Abdalla", "Ahmed"), ("Amina", "Khaled"),
    ("Ibrahim", "Salah"), ("Samira", "Hussein"), ("Khalid", "Omar"), ("Amira", "Hamid"),
    ("Hassan", "Abdu"), ("Rania", "Youssef"), ("Abdelrahman", "Ismail"), ("Nadia", "Kamal"),
    ("Ismail", "Adam"), ("Aziza", "Saleh"), ("Amir", "Elhassan"), ("Sahar", "Awad"),
    ("Ali", "Al-Mansoori"), ("Fatimah", "Abdullah"), ("Mohammed", "Saleh"), ("Aisha", "Al-Awadi"),
    ("Omar", "Al-Harazi"), ("Layla", "Al-Mazrouei"), ("Khaled", "Ahmed"), ("Safiya", "Al-Haddad"),
    ("Ahmed", "Al-Masri"), ("Noura", "Al-Qubaisi"), ("Faisal", "Al-Jabali"), ("Hana", "Al-Habib"),
    ("Abdul Rahman", "Al-Ali"), ("Salwa", "Al-Yamani"), ("Hamid", "Al-Badawi"), ("Sara", "Al-Makki"),
    ("Salah", "Al-Hakimi"), ("Amal", "Al-Bakri"), ("Tariq", "Al-Riyami"), ("Reem", "Al-Ghazali"),
    ("Liam", "Murphy"), ("Aoife", "Kelly"), ("Sean", "O'Connor"), ("Emma", "Byrne"),
    ("Conor", "Ryan"), ("Ciara", "Doyle"), ("Patrick", "Walsh"), ("Saoirse", "O'Sullivan"),
    ("Michael", "Kennedy"), ("Aisling", "Collins"), ("Darragh", "Brennan"), ("Niamh", "Murray"),
    ("David", "Byrne"), ("Kate", "Murphy"), ("Shane", "Gallagher"), ("Eilis", "Doyle"),
    ("Brian", "Kelly"), ("Siobhan", "Duffy"), ("John", "O'Neill"), ("Orlaith", "McLaughlin"),
    ("Mary-Jane", "Smith"), ("Juan-Carlos", "Gonzalez"), ("Jean-Luc", "Dubois"),
    ("Maria-Luisa", "Martinez"), ("Anna-Maria", "Papadopoulos"), ("John-Paul", "Anderson"),
    ("Juanita-Maria", "Lopez"), ("Lily-Rose", "Johnson"), ("Sophie-Anne", "Dupont"),
    ("José-Luis", "Ramirez"), ("Chi-Chi", "Chen"), ("Isabella-Maria", "Ricci"),
    ("Rosa-Linda", "Garcia"), ("Anne-Marie", "Martin"), ("Maria-Jose", "Alvarez"),
    ("Alessandra-Maria", "Rossi"), ("Ines-Maria", "Ferreira"), ("Hugo-Emanuel", "Ortega"),
    ("Mei-Ling", "Wang"), ("Luis-Fernando", "Hernandez"),("Aram", "Hakobyan"), ("Lusine", "Grigoryan"),
    ("Levon", "Sarkisian"),("Ani", "Khachatryan"),("Vardan", "Baghdasarian"),("Tatevik", "Papazian"),
    ("Ashot", "Melikyan"),("Silva", "Avagyan"),("Hovhannes", "Ter-Grigoryan"),("Narine", "Hovhannisian"),
    ("Arsen", "Hakobyan"),("Liana", "Martirosian"),("Tigran", "Babayan"),("Anahit", "Keshishian"),
    ("Gegham", "Mirzoyan"),("Lilit", "Mkrtchyan"),("Karen", "Hovsepyan"),("Sona", "Harutyunyan"),
    ("Armen", "Sarkissian"),("Anna", "Sargsyan"),("Miguel", "Silva"),("Ana", "Rodrigues"),
    ("João", "Pereira"),("Sofia", "Santos"),("Diogo", "Fernandes"), ("Carolina", "Lima"),
    ("André", "Oliveira"), ("Mariana", "Costa"), ("Francisco", "Sousa"),("Beatriz", "Martins"),
    ("Pedro", "Alves"), ("Inês", "Moreira"),("Tiago", "Ribeiro"),("Laura", "Pereira"),
    ("Bruno", "Cardoso"),("Catarina", "Ferreira"),("David", "Gomes"),("Filipa", "Barbosa"),
    ("Ricardo", "Santos"),("Clara", "Teixeira"),("Ahmed", "Al-Mahjoub"),
    ("Amina", "El-Mansouri"),("Ali", "Abdelaziz"),("Fatima", "Ibrahim"),
    ("Hassan", "Al-Jabir"),("Layla", "Abidi"),("Khalid", "Khalifa"),("Samira", "Al-Mansuri"),
    ("Mohammed", "Omar"),("Rania", "Al-Gaddafi"),("Youssef", "Ahmed"),("Nadia", "Saleh"),
    ("Amir", "Hassan"),("Dalia", "El-Mazari"),("Kareem", "Hadi"),("Leila", "Al-Farouk"),
    ("Tarik", "Abdullah"),("Soraya", "Al-Najjar"),("Ayman", "El-Abbas"),("Hala", "Khadim"),
    ("Batbold", "Jargal"),("Tsolmon", "Ganbaatar"),("Erdenebold", "Tsend"),("Narantuya", "Bat-Erdene"),
    ("Enkhjargal", "Ochir"),("Tuvshintur", "Turbat"),("Anu", "Chinbat"),("Ganbayar", "Janchiv"),
    ("Uranchimeg", "Munkh-Erdene"),("Naranbaatar", "Baasansuren"),("Davaajav", "Luvsan"),
    ("Tungalag", "Tumendelger"),("Altantsetseg", "Badamkhand"),("Batzorig", "Batbaatar"),
    ("Oyuntsetseg", "Gantumur"),("Batzorig", "Bold"),("Ankhbayar", "Bayarsaikhan"),
    ("Sarangerel", "Erdene"),("Batsukh", "Luvsandorj"),("Munkh-Orgil", "Jargalsaikhan"),
    ("Kwame", "Addo"),("Akua", "Asante"),("Kwabena", "Boateng"),("Abena", "Osei"),
    ("Kwame", "Ansah"),("Ama", "Darko"),("Kwabena", "Mensah"),("Akosua", "Ampofo"),
    ("Kofi", "Adu"),("Abena", "Nyarko"),("Kwaku", "Amoah"),("Afia", "Boateng"),
    ("Kwame", "Acheampong"),("Adwoa", "Ofori"),("Kwabena", "Owusu"),("Ama", "Yeboah"),
    ("Kwadwo", "Adjei"),("Akosua", "Boateng"), ("Kojo", "Asare"), ("Efia", "Danso"),
    ("Ivan", "Petrov"), ("Maria", "Ivanova"),("Yuriy", "Smirnov"),("Kateryna", "Kuznetsova"),
    ("Oleksandr", "Sokolov"),("Natalia", "Volkova"),("Andriy", "Morozov"),
    ("Olena", "Pavlova"), ("Dmytro", "Sidorov"), ("Tetiana", "Orlova"),
    ("Yevhen", "Novikov"), ("Anastasia", "Voronina"),("Oleksii", "Kozlov"),("Yuliia", "Popova"),
    ("Serhii", "Belyakov"),("Marina", "Fedorova"),("Roman", "Egorov"),
    ("Daria", "Nikitina"),("Andriy", "Voronov"),("Larisa", "Sokolova"),("Kwame", "Addo"),
    ("Akua", "Asante"),("Kwabena", "Boateng"),("Abena", "Osei"),("Kwame", "Ansah"),
    ("Ama", "Darko"),("Kwabena", "Mensah"),("Akosua", "Ampofo"),
    ("Kofi", "Adu"),("Abena", "Nyarko"),("Kwaku", "Amoah"),("Afia", "Boateng"),
    ("Kwame", "Acheampong"),("Adwoa", "Ofori"),("Kwabena", "Owusu"),("Ama", "Yeboah"),
    ("Kwadwo", "Adjei"),("Akosua", "Boateng"),("Kojo", "Asare"),("Efia", "Danso"),
    ("Kwame", "Addo"),("Akua", "Asante"),("Kwabena", "Boateng"),("Abena", "Osei"),
    ("Kwame", "Ansah"), ("Ama", "Darko"), ("Kwabena", "Mensah"),
    ("Akosua", "Ampofo"),("Kofi", "Adu"),("Abena", "Nyarko"),
    ("Kwaku", "Amoah"),("Afia", "Boateng"), ("Kwame", "Acheampong"),
    ("Adwoa", "Ofori"),("Ama", "Yeboah"),("Kwadwo", "Adjei"),("Akosua", "Boateng"),
    ("Kojo", "Asare"),("Efia", "Danso"),("Akio", "Kumari"),("Rahul", "Hiroko"),
    ("Jitendra", "Rina"),("Yudai", "Sarala"),("Haruki", "Priyanka"),("Takashi", "Kavita"),
    ("Daisuke", "Lakshmi"),("Kazuki", "Sunita"),("Yasuo", "Mina"),("Sushil", "Parvati"),
    ("Ryota", "Deepika"),("Kojiro", "Sarika"),("Hiroshi", "Ananya"),("Tetsuya", "Nalini"),
    ("Kenta", "Meera"),("Takayuki", "Jyoti"),("Yoshiko", "Arjun"),("Masumi", "Sudha"),
    ("Yuto", "Asha"),("Rajesh", "Anjali"),("Shohei", "Swara"),("Ravi", "Aarti"),
    ("James", "Smith"),("Emily", "Johnson"),("Daniel", "Brown"),("Olivia", "Taylor"),
    ("Thomas", "Wilson"),("Charlotte", "Evans"),("William", "Turner"),
    ("Sophia", "White"),("Samuel", "Clark"),("Isabella", "Hall"),
    ("Benjamin", "Wright"),("Lily", "Davis"),("Henry", "Martin"),("Grace", "Lewis"),
    ("David", "Harris"),("Amelia", "Green"),("Michael", "Robinson"),("Elizabeth", "Baker"),
    ("Joseph", "Hughes"),("Jessica", "Carter"),("Mohamed", "Ben Ali"),("Fatima", "Khemiri"),
    ("Ahmed", "Nouri"),("Amina", "Bouaziz"),("Hichem", "Ben Youssef"),("Leila", "Mabrouk"),
    ("Walid", "Sassi"),("Salma", "Haddad"),("Anis", "Chakroun"),("Amira", "Fathi"),
    ("Nizar", "Gharbi"),("Aicha", "Slimani"),("Marouane", "Khaled"),("Hayet", "Jebali"),("Ziad", "Ben Amar"),
    ("Samira", "Abassi"),("Chaker", "Hachemi"),("Wafa", "Belhadj"),("Mounir", "Mansouri"),("Rania", "Ben Salem"),
    ("Ivan", "Petrov"),("Maria", "Ivanova"),("Georgi", "Georgiev"),("Stefani", "Dimitrova"),
    ("Dimitar", "Ivanov"),("Elena", "Marinova"),("Nikolay", "Popov"),("Anna", "Petrova"),
    ("Petar", "Dimitrov"),("Tanya", "Georgieva"),("Hristo", "Kolev"),("Viktoriya", "Kostova"),
    ("Stefan", "Angelov"),("Emiliya", "Atanasova"),("Simeon", "Dimitrov"),("Gergana", "Ivanova"),
    ("Lyubomir", "Stoyanov"),("Zoya", "Petrova"),("Iliyan", "Andreev"),("Desislava", "Kirova"),
    ("Aung", "Min"),("Suu", "Kyi"),("Htet", "Lin"),("Thandar", "Tun"),("Ye", "Min"),("Phyu", "Phyu"),
    ("Naing", "Aung"),("Khin", "Thet"),("Win", "Hlaing"),("Myo", "Win"),("Su", "Myat"),
    ("Zaw", "Htay"),("Nanda", "Hlaing"),("Hlaing", "Min"),("Khin", "Mar"),("Soe", "Myint"),
    ("Yin", "Win"),("Zaw", "Htet"),("Nilar", "Aye"),("Maung", "Maung"),("Ahmed", "Al-Thani"),
    ("Fatima", "Ahmed"),("Khalid", "Ibrahim"),("Noor", "Abdullah"),("Yousef", "Al-Mansoori"),
    ("Aisha", "Mohammed"),("Hassan", "Al-Thani"),("Mariam", "Khalid"),("Ali", "Al-Majid"),
    ("Layla", "Nasser"),("Hamad", "Al-Kuwari"),("Sheikha", "Al-Sulaiti"),
    ("Saad", "Al-Attiyah"),("Latifa", "Ali"),("Mubarak", "Al-Hajri"),("Nouf", "Al-Mohannadi"),
    ("Rashid", "Al-Mahmoud"),("Maryam", "Al-Khater"),("Fahad", "Al-Mulla"),("Laila", "Al-Thani"),
    ("Aizada", "Marat"), ("Assel", "Tuleubayeva"), ("William", "Shabecoff")]

    return names

def middle_names():
    middle_names = ["Marie", "Wei", "Ahmed", "Sofia", "Giovanni", "Hiroshi", "Anika", "Dimitri", "Carmen", "Jamal",
    "Svetlana", "Mei", "Isabella", "Akihiko", "Priya", "Jean", "Vladislav", "Lucia", "Jia", "Nour",
    "Elena", "Koji", "Akshay", "Aleksandra", "Mateo", "Sakura", "Aditi", "Élise", "Sergey", "Antonella",
    "Lian", "Yasmin", "André", "Hikari", "Deepak", "Irina", "Valentina", "Wei", "Basim", "Amara",
    "Michelle", "Hiroto", "Simran", "Aleksander", "Marisol", "Sophia", "Surya", "Nikolai", "Eloise",
    "Zara", "Luka", "Mei-Ling", "Kamala", "Raul", "Alessia", "Issei", "Sébastien", "Anastasia",
    "Syed", "Rafael", "Taisuke", "Sahar", "Alexander", "Priyanka", "Elara", "Sachiko", "Giuseppe",
    "Thi", "Sofia", "Ahmed", "Anna", "Surya", "Maria", "Kai", "Viktor", "Zara", "Elena", "Mei",
    "Basim", "Isabella", "Maxim", "Simran", "Malik", "Victoria", "Taro", "Léa", "Anastasios",
    "Akiko", "Ravi", "Ilona", "Alessandro", "Nisha", "Andréa", "Fatima", "Andrei", "Kamala", "Aaliyah",
    "Enrique", "Sofia", "Meilin", "Gabriel", "Aisha", "Carlos", "Meera", "Matteo", "Hana", "Nikolai", "Isabella", "Rafiq", "Elisabeth", "Zane", "Luna", "Maximilian", "Anisa", "Lorenzo", "Ayesha", "Mateusz", "Mira", "Xander", "Sari",
    "Alessio", "Lila", "Roman", "Aria", "Leandro", "Zara", "Nico", "Priyanka", "Santiago", "Mila",
    "Oliver", "Nina", "Dominic", "Leila", "Antonio", "Sofia", "Luca", "Inaya", "Leonardo", "Samara",
    "Nathaniel", "Amelia", "Raphael", "Nadia", "Sebastian", "Elena", "Elias", "Salma", "Cristian",
    "Ava", "Lucas", "Sara", "Theodore", "Zainab", "Daniel", "Amina", "Gabriella", "Eva",
    "Adrian", "Amara", "Emanuel", "Ella", "Alexis", "Zaina", "David", "Lina", "Nikolas", "Maya",
    "Francesco", "Nour", "Emmanuel", "Safia", "Dominik", "Amina", "Kai", "Zahra", "Julian", "Yasmina",
    "Antonia", "Isra", "Fabian", "Amina", "Mariano", "Layla", "Gabrielle", "Amina", "Dario", "Yara",
    "Mathias", "Laila", "Caleb", "Sofie", "Lucian", "Sophie", "Emiliano", "Layla", "Eduardo", "Farida",
    "Matias", "Hadiya", "Luigi", "Zoya", "Anton", "Nyla", "Alejandro", "Sahar",
    "Lucia", "Kaden", "Adela", "Elliott", "Leilani", "Kieran", "Esmeralda", "Wesley", "Amina", "Atticus",
    "Elowen", "Cormac", "Cecilia", "Jasper", "Giselle", "Finnian", "Dahlia", "Everett", "Mireya",
    "Caspian", "Seraphina", "Lachlan", "Aurelia", "Gideon", "Elara", "Evangeline", "Nikolai", "Odette", "Ezekiel",
    "Valentina", "Dashiell", "Marcella", "Thaddeus", "Guinevere", "Orion", "Esperanza", "Solomon", "Annalise", "Sullivan",
    "Alessandra", "Leocadia", "Xander", "Apollonia", "Finnegan", "Katerina", "Dorian", "Ophelia", "Leander", "Eulalia",
    "Octavian", "Anastasia", "Aurelian", "Marceline", "Aurelius", "Magnolia", "Isidore", "Eulalie", "Lysander", "Fidelia",
    "Cassian", "Zephyrine", "Aurelio", "Calliope", "Augustine", "Severine", "Peregrine", "Ottoline", "Sylvester", "Eudora",
    "Balthazar", "Theodosia", "Valerian", "Euphemia", "Valentinian", "Eulalio", "Ignatius", "Esperanto", "Maximilian", "Evelina",
    "Demetrius", "Persephone", "Eleutherios", "Isolde", "Nereus", "Elysia", "Theophanes", "Ottavia", "Ptolemy", "Celestina",
    "Ambrosius", "Calista", "Isidoro", "Amaryllis", "Panagiotis", "Hermione", "Proteus", "Sophronia", "Seraphim", "Eupraxia",
    "Epiphanios", "Elestrenia",
    "Kwame", "Sekai", "Adeola", "Thabo", "Nia", "Ephraim", "Kadija", "Tendai", "Kofi", "Chinwe",
    "Tarik", "Zola", "Ifeoma", "Osei", "Imani", "Ayodele", "Nkosana", "Amara", "Tope", "Tariro",
    "Lumumba", "Asante", "Aissatou", "Mandla", "Nabila", "Mandisa", "Siyabonga", "Amiri", "Ayana", "Sekou",
    "Zahara", "Akintunde", "Ayotunde", "Kemba", "Tawia", "Zainabu", "Lwazi", "Adanna", "Zanele", "Chikondi",
    "Mabinty", "Zekariya", "Kwabena", "Jamila", "Nande", "Jabari", "Niazi", "Tariq", "Amina", "Kwasi",
    "Kanika", "Jendayi", "Kwadwo", "Lalage", "Malaika", "Chinonye", "Omarion", "Nala", "Emeka", "Keketso",
    "Lethabo", "Zahur", "Dandara", "Kwame", "Sefu", "Amina", "Thabiti", "Lule", "Jaha", "Nkrumah", "Tendai",
    "Amadou", "Asim", "Mawusi", "Adele", "Lethabo", "Nkruma", "Aziza", "Chinwe", "Ibuka", "Nadia", "Makana",
    "Ousmane", "Katura", "Thandiwe", "Sango", "Najwa", "Chukwuma", "Njeri", "Esi", "Siyabulela", "Adegoke",
    "Tendai", "Akachi", "Kwabena", "Esi", "Ayize", "Asante", "Kwasi", "Thembeka", "Malaika", "Kagiso",
    "Akio", "Kumari", "Rahul", "Hiroko", "Jitendra", "Rina", "Yudai", "Sarala", "Haruki", "Priyanka",
    "Takashi", "Kavita", "Daisuke", "Lakshmi", "Kazuki", "Sunita", "Yasuo", "Mina", "Sushil", "Parvati",
    "Ryota", "Deepika", "Kojiro", "Sarika", "Hiroshi", "Ananya", "Tetsuya", "Nalini", "Kenta", "Meera",
    "Takayuki", "Jyoti", "Yoshiko", "Arjun", "Masumi", "Sudha", "Yuto", "Mira", "Rajesh", "Aarti",
    "Shohei", "Swara", "Ravi", "Anjali", "Hideo", "Lalita", "Kazuko", "Neel", "Maya", "Ryosuke",
    "Kamala", "Shogo", "Manju", "Yui", "Asha", "Kenjiro", "Jasmine", "Yuki", "Kiran", "Daiki",
    "Sonam", "Akira", "Jaya", "Haruto", "Sarla", "Tetsuro", "Ananya", "Shiori", "Sakshi", "Noboru",
    "Neha", "Mitsuru", "Indira", "Asuka", "Ishita", "Hinata", "Sanjana", "Kiyomi", "Anushka", "Satoru",
    "Vasanti", "Seiji", "Dipti", "Riku", "Aruna", "Ryoko", "Rashmi", "Kanako", "Poonam", "Ryusei",
    "Padma", "Maki", "Varun", "Madhuri", "Daichi", "Kalpana", "Yuuto", "Amrita", "Hinako", "Nandini"]

    return middle_names

def last_names():
    names = [
    "Andersson", "Patelov", "O'Malik", "Nguyenstein", "Santiago", "Wangster",
    "Chávezquez", "Goldblatt", "Petrovich", "Mendoza", "Khanov", "Caruso",
    "Lópezki", "Mironová", "DuBois", "Tanaka", "Rodriguezki", "Schneiderman",
    "Quinones", "Brownstein", "Jovanović", "MacIntyrescu", "Almeida", "Itofamé",
    "Gonzálezová", "Sánchezberg", "Schwartzman", "Santoski", "Petrović", "Wagner",
    "Fernandez", "Kimura", "Santorini", "D'Costa", "Aliyev", "Kowalskova",
    "Müllerstein", "Chenberg", "Jansen", "Lópezquez", "Ibrahimov", "Svensson",
    "Leblanc", "Kimball", "Akhtar", "Castellanos", "Van der Berg", "Napolitano",
    "García-Mendoza", "O'Callaghan", "Ilyin", "Petrov", "McAllisterová",
    "Fernandezki", "O'Connor", "Tanakovich", "Parková", "Caruso-González",
    "Antonov", "Szymanska", "Duboisová", "Wongstein", "Castellano", "Kimballa",
    "García-Lopez", "Rossi", "Smithberg", "Kuznetsová", "Murphy", "Tanakovsky",
    "Leeberg", "Papadopoulos", "Chan", "Mironovich", "Brownsteinová", "Kimura-García",
    "Almeida-Santos", "O'Neill", "Rodríguez-Mendoza", "Anderssonová", "Gupta",
    "Kowalski", "Patelová", "Tanakaschwartz", "Chenkov", "Duboisi", "Jovanov",
    "Wagnerstein", "López-Smith", "Müllerová", "Petrovićski", "Chávez-Rodriguez",
    "Kimballstein", "Gonzalezov", "Santoski-Mendoza", "Santiago-Smith", "Wagnerberg",
    "Fernández-Patel", "Tanakasanchez", "Ilyinov","Hernandezov", "Smithson", "Petrovski",
    "Gonzálezquez", "Kimballberg", "Patelovich","Santiago-Gupta",
    "Müllersteinová", "Rodriguez-Goldman", "Santorinov", "Tanakaschwartzberg",
    "Jovanová", "O'Connorskaya", "Ibrahimovich", "Leebergov", "Akhtarnikov", "Santos-MacIntyre",
    "Wangberg", "Duboisovich", "Almeida-Chen", "Svenssonstein", "Castellanov", "Napolitanoski",
    "García-Andersson", "Quinones-González", "Chávez-Rossi", "Wongsteinov", "O'Murphyski",
    "Kimura-Santos", "Itofamé-Müller", "McAllisternikova", "Fernandez-Chan", "López-Caruso",
    "Wagnerbergov", "Brownstein-García", "Antonovich", "Caruso-Kowalski", "DuBois-Mironov",
    "Patel-López", "Rodriguez-Petrov", "Chenstein", "Kimball-Tanaka", "Goldblattová", "Santos-Sánchez",
    "Smith-Chávez", "Gonzalezovich", "Mendoza-Schwartz", "Ilyin-Kowalska", "Müller-Santiago",
    "O'Callaghanskaya", "Fernandez-Kimura", "Jansenov", "Petrovic-Gupta", "Almeida-Wong",
    "Szymanski-Papadopoulos", "Ilyin-Patel", "Caruso-Khan", "Smithsonov", "Kimballa-López",
    "O'Neillstein", "Tanakamurphy", "Rodriguez-Chenkov", "Müller-Lee", "García-Castellano",
    "Petrovich-Kimball", "Gonzalez-Santoski", "Santos-Chavez", "Fernandez-Petrovski", "Ibrahimova",
    "Wagner-Gupta", "Chen-Lopez", "Petrovic-Wang", "Kimura-Mironova", "Akhtar-Kowalski",
    "Lee-Brownstein", "Ilyinová", "McAllister-Chavez", "Jovanovićstein", "Sánchez-Patelová",
    "Müller-Rossi", "Svensson-Brown", "Dubois-Petrovich", "Fernandez-Tanaka", "Napolitano-García",
    "Wangsterov", "Chávez-Smith", "Lópezkov", "Castellanoski", "Santos-Berg", "Tanaka-Papadopoulos",
    "Quinones-Tanaka", "Akhtar-Schwartz", "Chenbergová", "Rodriguez-McAllister", "Brownstein-Tanakovsky",
    "Szymanska-Goldblatt", "O'Malikovich", "Petrova", "Almeida-DuBois", "Itofamé-Smithberg",
    "Cruz", "Li", "Singh", "Kim", "Wong", "Jones", "Chen", "Patel", "Smith", "Tran",
    "Lee", "López", "Brown", "García", "Nguyen", "Johnson", "Santos", "Ali", "O'Neil", "Kumar",
    "Mendoza", "Pérez", "Taylor", "Adams", "Wu", "Lewis", "Castro", "Chang", "Ortiz", "White",
    "Khan", "Chenkov", "Silva", "Park", "Wu-Tanaka", "Vargas", "Kimball", "Gomez", "Rivera", "Cooper",
    "Tan", "Akhtar", "Patelová", "Ross", "Torres", "Huang", "Gray", "Caruso", "Green", "Ito",
    "Baker", "Clark", "Santoro", "DuBois", "Schmidt", "Sánchez", "Jensen", "Kowalski", "Gupta", "Anton",
    "Kimura", "Wongberg", "Adamski", "Cruzová", "O'Connor", "Mitchell", "Santoski", "Lópezquez", "Anders", "Ilyin",
    "Fernandezki", "Chenberg", "Wangster", "Black", "Patelovich", "Larsen", "Fernandezquez", "Lopezstein", "Smithson", "Tanakov",
    "Santosov", "Rossi", "Petrovski", "Akhtarová", "Svensson", "Szymanska", "Jovanović", "Ivanov", "Wagner", "Müller",
    "O'Neal", "Kimballstein", "Sánchez-Gupta", "Petrovich", "Chenková", "Mironov", "Wang", "Szymanski-Patel", "O'Connell", "Fernandezstein",
    "Baker", "Fisher", "Hunter", "Turner", "Weaver", "Fletcher", "Walker", "Carter", "Miller", "Taylor",
    "Farmer", "Potter", "Cooper", "Archer", "Singer", "Foster", "Mason", "Harper", "Parker", "Butcher",
    "Smith", "Knight", "Roper", "Porter", "Gardner", "Brewer",
    "Abaev", "Dzhumagaliyev", "Ismagulov", "Nurmukhambetov", "Tulegenov",
    "Zharkinov", "Kozhakhmetov", "Yermukhambetov", "Tokayev", "Zholdasov",
    "Sagyndykova", "Sagyntayev", "Zhumabayev", "Aitkhozhin", "Mukhtarov",
    "Abayeva", "Dzhumagaliyeva", "Ismagulova", "Nurmukhambetova", "Tulegenova",
    "Zharkinova", "Kozhakhmetova", "Yermukhambetova", "Tokayeva", "Zholdasova",
    "Sagyndykov", "Sagyntayeva", "Zhumabayeva", "Aitkhozhina", "Mukhtarova",
    "Jumabekov", "Jumabekova", "Abdyldaev", "Abdyldaeva", "Orozobekov", "Orozobekova",
    "Japarov", "Japarova","Nuraliev", "Nuralieva","Mambetov", "Mambetova",
    "Uulu", "Uulova","Baigazy", "Baigazieva","Doolotbekov", "Doolotbekova",
    "Turgunbaev", "Turgunbaeva","Niazov", "Niazova","Akmatov", "Akmatova",
    "Beleren", "Vess", "Nalaar", "Wildspeaker", "Goldmane", "Tirel", "Bolas", "Jura", "Revane", "Vol",
    "Markov", "Reid", "Verada", "Zarek", "Rade", "Rai", "Kord", "Kens",
    "Kenrith", "Mu", "Blinz", "Glorp", "Drantz",
    "Splint", "Grivs", "Blark", "Zlunt", "Crisp", "Klomp", "Slurge",
    "Plint", "Quarp", "Snivs", "Frinz", "Thworp", "Slint", "Trisp", "Plonk", "Vlarp", "Krimp",
    "Znarl", "Quirk", "Twixt", "Sklarp", "Crink", "Flink", "Jlort", "Prink", "Splinx", "Glint",
    "Trinz", "Klork", "Fworp", "Squint", "Blonk", "Slurk", "Drinx", "Grinx", "Znorp", "Plork",
    "Splork", "Glurp", "Quorp", "Klonk", "Frinx", "Squirk", "Snorp", "Grint", "Jlarp", "Crort",
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Davis", "Miller", "Wilson", "Moore", "Taylor",
    "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson",
    "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen", "Young", "Hernandez", "King",
    "Wright", "Lopez", "Hill", "Scott", "Adams", "Gonzalez", "Nelson", "Carter",
    "Mitchell", "Perez", "Roberts", "Turner", "Phillips", "Campbell", "Parker", "Evans", "Edwards", "Collins",
    "Stewart", "Sanchez", "Morris", "Rogers", "Reed", "Cook", "Morgan", "Bell", "Murphy", "Bailey",
    "Rivera", "Cooper", "Cox", "Long", "Peterson", "James", "Watson", "Diaz", "Hayes",
    "Myers", "Barnes", "Fisher", "Hall", "Powell", "Perry", "Smith", "Johnson", "Williams", "Brown",
    "Jones", "Davis", "Miller", "Wilson", "Moore", "Taylor", "Anderson", "Thomas", "Jackson", "White",
    "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson", "Lewis", "Lee", "Tulebayeva", "Marat", "Maratt"
    ]
    return names


def first_names():
    names = [
    "Zarina", "Kaelum", "Thalina", "Marvik", "Soraya", "Quillon", "Esmera", "Kyland", "Azena", "Harun",
    "Linara", "Zephyr", "Nalani", "Xander", "Isolta", "Elestia", "Zephyra", "Jorvik", "Olymira", "Caelus",
    "Talitha", "Ronara", "Tyrian", "Seraphin", "Vaelis", "Kalina", "Thandor", "Eliora", "Azariah", "Liora",
    "Quinlan", "Varro", "Sylas", "Faelan", "Jovana", "Soren", "Evelin", "Orin", "Maelis", "Anara", "Calix",
    "Selena", "Zephyrine", "Vaelith", "Thaleon", "Nerida", "Zorin", "Azalea", "Lyron", "Elysse", "Kiralyn",
    "Kaelara", "Tavion", "Olyria", "Esrynn", "Isolde", "Galen", "Thalara", "Jaren", "Orinthea", "Kaelys",
    "Sylas", "Illyria", "Xandara", "Nerys", "Seraphia", "Vaelor", "Aris", "Halcyon", "Calista", "Ilysia",
    "Kyler", "Valeria", "Ellion", "Zephyros", "Thalora", "Sylar", "Isabeau", "Zorana", "Elysian", "Kaelira",
    "Xarion", "Tavira", "Nerian", "Zalira", "Caelira", "Thalorin", "Azura", "Jorlina", "Seraphus", "Lyrica",
    "Vaelis", "Alistair", "Thandara", "Iliona", "Kaelith", "Orlan", "Naelis", "Varina", "Aricent", "Azelie",
    "Zephyrus", "Amara", "Lioran", "Myrrh", "Thessia", "Erevan", "Kasimir", "Linnea", "Elysian",
    "Sorrel", "Zaynab", "Nyx", "Thandor", "Caelina", "Finnick", "Nalira", "Jocasta", "Zyanya", "Tyrell",
    "Eirian", "Vashti", "Alaric", "Seren", "Isolde", "Elara", "Osric", "Lyris", "Zephyria", "Thalorin",
    "Amira", "Kaelar", "Isannah", "Lirael", "Jorvik", "Vaelor", "Zayla", "Olyra", "Calix", "Azena",
    "Thora", "Ryland", "Ailith", "Zephyr", "Sorenna", "Eirik", "Ione", "Thaleon", "Caelan", "Seraphis",
    "Althea", "Kaelan", "Iliona", "Zorina", "Liora", "Vaelith", "Tyrian", "Sylas", "Isola", "Thalina",
    "Azelia", "Eirys", "Naelis", "Ysara", "Calista", "Elikai", "Thallis", "Jorlina", "Alain", "Zylar",
    "Lysandra", "Vaelon", "Zorin", "Jivara", "Kaelis", "Iliad", "Selene", "Thalor", "Sorrelle", "Elowen",
    "Tyren", "Aeliana", "Iskandar", "Caelum", "Thalia", "Rysa", "Elsara", "Zephyrion", "Nerys", "Jorvika",
    "Azara", "Liraelle", "Vaelitha", "Sylar", "Elysia", "Nyxian", "Thandora", "Althean", "Isolde", "Caelira",
    "Aibek", "Aisha", "Altair", "Amina", "Aslan", "Ayim", "Bakyt", "Damir", "Dina", "Erlan",
    "Gulnaz", "Ilyas", "Inzhu", "Karim", "Kenzhe", "Kuralai", "Madina", "Madiyar", "Nurzhan", "Perizat",
    "Rauan", "Rayana", "Sabina", "Saken", "Saltanat", "Talgat", "Togzhan", "Ulyana", "Yerke", "Yersultan",
    "Zere", "Zhanar", "Zhansaya", "Zhibek", "Zhuldyz","Aibek", "Aigul", "Akylai",
    "Altynai", "Asylbek", "Begimai", "Cholpon", "Damira", "Ermek", "Gulnaz","Ilyas", "Janyl",
    "Jyldyz", "Karachach", "Kyzyl", "Malika", "Maral", "Nurbek", "Ormonbek", "Rysbek",
    "Sagyn", "Samat", "Taalai", "Talant", "Togolok", "Umut", "Uulu", "Urmat", "Yrys", "Zairbek", "Zhyldyz",
    "Zhumabek", "Zhyrgal", "Zhyrgul", "Zhanybek", "Jace", "Liliana", "Chandra", "Gideon", "Nissa", "Ajani",
    "Tezzeret", "Kiora", "Nahiri", "Sarkhan", "Sorin",
    "Ral", "Vraska", "Garruk", "Domri", "Venser", "Elspeth", "Kaya", "Ob Nixilis", "Dack",
    "Ashiok", "Tamiyo", "Xenagos", "Koth", "Tibalt", "Angrath", "Saheeli", "Nahiri", "Kinnan", "Emrakul",
    "Bolas", "Kari", "Kess", "Tawnos", "Freyalise", "Bruna", "Gisa", "Toshiro", "Jhoira", "Rafiq", "Estrid",
    "Yawgmoth", "Urza", "Nicol", "Kamahl", "Vela", "Marit", "Slimefoot", "Radha", "Tetsuo",
    "Amber", "Archer", "Autumn", "Basil", "Blaise", "Blaze", "Breeze", "Brook", "Chance", "Chase",
    "Clay", "Cliff", "Cole", "Cricket", "Cruz", "Dale", "Dawn", "Ember", "Faith", "Faye",
    "Fern", "Forrest", "Fox", "Gale", "Grace", "Hawk", "Holly", "Hope", "Jade", "Jasper",
    "Jay", "Jett", "Lake", "Leaf", "Leo", "Lily", "Luna", "Meadow", "Mist", "Moon", "Moss",
    "Ocean", "Onyx", "Paige", "Park", "Peace", "Pearl", "Phoenix", "Rain", "Ray", "Reed",
    "River", "Rose", "Rowan", "Sage", "Skye", "Snow", "Sol", "Spring", "Star", "Storm",
    "Summer", "Sunny", "Swift", "Vale", "Wolf", "Yarrow", "Zephyr",
    "Krys", "Mourt", "Blaine", "Dax", "Ryn", "Joss", "Quinn", "Bryn", "Shay", "Lorne",
    "Beck", "Rhys", "Wren", "Gray", "Sloane", "Rook", "Vail", "Lark", "Zane", "Blake",
    "Chase", "Greer", "Jayce", "Skye", "Faye", "Zed", "Vale", "Rain", "Bex", "Gage",
    "Nell", "Jace", "Kai", "Fynn", "Blaise", "Kade", "Reece", "Blythe", "Chance", "Lorne",
    "Rayne", "Tyce", "Sloane", "Nash", "Mayne", "Quin", "Raze", "Tryst", "Kaine", "Rynn",
    "Beck", "Mace", "Brant", "Vale", "Twain", "Bryn", "Blane", "Clay", "Lorne", "Tane",
    "Zayn", "Quinn", "Klaas", "Raze", "Jett", "Wynn", "Raul", "Rook", "Drake", "Shaine",
    "Grey", "Kane", "Ross", "Reece", "Blake", "Reeve", "Vann", "Heath", "Bree", "Flint",
    "Shea", "Locke", "Zade", "Dash", "Niles", "Flynn", "Lorne", "Vance", "Gail", "Rhys",
    "Judd", "Wray", "Blay", "Chase", "Gage", "Royce", "Shayne", "Tad", "Flint", "Quade",
    "Aiden", "Sofia", "Muhammad", "Olivia", "Lucas", "Mia", "Noah", "Ava", "Isabella", "Liam",
    "Zoe", "Mason", "Sophia", "Harper", "Amelia", "Elijah", "Evelyn", "Benjamin", "Charlotte", "Samuel",
    "Abigail", "Alexander", "Emily", "Michael", "James", "Grace", "Lily", "Emma", "Sofia", "Amelia",
    "Ava", "Sophia", "Lily", "Charlotte",
    "Zara", "Leo", "Hazel", "Eli", "Naomi", "Caleb", "Luna", "Owen", "Maya", "Xavier",
    "Aria", "Felix", "Nova", "Caleb", "Seraphina", "Max", "Eloise", "Dylan", "Freya", "Jackson",
    "Delilah", "Isaac", "Penelope", "Elijah", "Sadie", "Kian", "Evangeline", "Arlo", "Aurora", "Felix",
    "Leilani", "Atticus", "Eliza", "Mateo", "Isla", "Gabriel", "Arabella", "Micah", "Violet", "Ezekiel",
    "Serenity", "Ezra", "Adeline", "Luca", "Isabelle", "Noah", "Amara", "Caleb", "Elodie", "Sebastian", "Assel", "Aizada"
    ]

    return names





def distractor_spans():
    spans = ["In the heart of the bustling city lies Central Park, a vast green oasis teeming with life. Towering skyscrapers surround this urban marvel, creating a stark contrast to its serene ambience. The park's iconic landmarks, such as Bethesda Terrace and Strawberry Fields, attract throngs of tourists and locals alike, seeking respite from the city's relentless pace. The Central Park Zoo, home to a diverse array of animals, offers a captivating experience for families and nature enthusiasts. From the lush meadows to the winding pathways, Central Park is a captivating destination that captivates the senses and showcases the harmonious coexistence of nature and urbanity.",
 'The Eiffel Tower, located in Paris, is an iconic landmark that attracts countless tourists each year. The Great Barrier Reef, off the coast of Australia, is the world\'s largest coral reef system and a UNESCO World Heritage Site. Mount Everest, situated in the Himalayas, is the highest peak on Earth and a prominent destination for mountaineers from around the globe. The Amazon Rainforest, spanning several countries in South America, is renowned for its rich biodiversity and is often referred to as the "lungs of the planet." The Taj Mahal, a mausoleum in India, is a masterpiece of Mughal architecture and a symbol of eternal love.',
 "Welcome to the enchanting city of Paris, where the Eiffel Tower proudly stands and the Louvre Museum holds a treasure trove of artistic marvels. As you stroll along the romantic Seine River, you'll be captivated by the Gothic grandeur of Notre-Dame Cathedral and the vibrant atmosphere of the Champs-Élysées. Don't miss the opportunity to sample exquisite French cuisine at renowned establishments like La Tour d'Argent or indulge in a shopping spree at iconic stores such as Galeries Lafayette. Paris, a symbol of beauty and culture, awaits your exploration.",
 "In the bustling city of New York, a famous landmark stands tall - the Empire State Building. Tourists from all over the world flock to this iconic skyscraper to admire its breathtaking views of the city. Nearby, Central Park offers a serene retreat from the urban chaos, with its lush greenery and tranquil lakes. Just a few blocks away, the Rockefeller Center invites visitors to witness its vibrant ice-skating rink during the winter season. And let's not forget the Statue of Liberty, a symbol of freedom and democracy, standing proudly in the New York Harbor.",
 'The Eiffel Tower stood tall, overlooking the city of Paris. The Amazon rainforest, with its diverse flora and fauna, was a sight to behold. The Great Barrier Reef, home to colorful coral and vibrant marine life, spanned the coast of Australia. The Taj Mahal, an architectural masterpiece, attracted tourists from all over the world. Mount Everest, the highest peak in the world, challenged climbers with its daunting summit. The Louvre Museum, housing iconic artworks such as the Mona Lisa, was a cultural hub in the heart of France. The Sahara Desert, with its vast expanse of sand dunes, stretched endlessly through northern Africa. The Statue of Liberty, a symbol of freedom, welcomed immigrants arriving in New York City. The Galapagos Islands, known for their unique wildlife species, were a paradise for nature enthusiasts. The Acropolis, perched high in Athens, showcased ancient Greek architecture at its finest.',
 "In the vibrant city of Tokyo, nestled in the bustling district of Shibuya, stands the iconic Shibuya Crossing. Surrounded by towering skyscrapers, this famous intersection is frequented by thousands of pedestrians each day. Adjacent to the crossing lies Hachiko Statue, a commemorative bronze sculpture of a loyal dog named Hachiko, known for his unwavering loyalty to his deceased owner. The Shibuya Station, a major transportation hub, connects the city's railway and subway lines, making it a vital hub for commuters and tourists alike. Nearby, Meiji Shrine, a serene oasis in the heart of the city, offers a peaceful retreat where visitors can experience the spiritual essence of Japan.",
 'In the heart of the bustling city, stands the grand and majestic Empire Tower, a symbol of architectural brilliance. Its gleaming glass facade reflects the shimmering lights of the surrounding Financial District, showcasing the bustling energy that permeates through its vibrant streets. Near the tower lies the sprawling Central Park, a tranquil oasis amidst the concrete jungle, adorned with lush greenery and picturesque pathways. Visitors can unwind on the banks of the serene Swan Lake or marvel at the captivating sculptures that adorn its beautifully landscaped gardens.',
 "In the enchanting land of Avaloria, nestled amidst the sprawling Dreamever Forest, lies the majestic Sapphire Citadel. Towering over the emerald-hued landscape, the Citadel is home to the revered Council of Elders, a group of wise mystics who safeguard the ancient Book of Arcane Wisdom. The book, said to contain the secrets of powerful spells and ancient prophecies, is cherished by the inhabitants of Avaloria, who believe it holds the key to their realm's future. In the depths of the Crystal Caverns, a place of mystic energy and dazzling gemstones, whispers of a long-lost artifact, the Chronos Crystal, have ignited a quest among brave adventurers seeking its mythical power. As legends intertwine and destinies unfold, the fate of Avaloria hangs in the balance, beckoning the courageous to embark on a perilous and extraordinary journey.",
 "The Eiffel Tower, located in Paris, France, is an iconic landmark that attracts millions of tourists each year. The tower, stands at a height of 330 meters and offers stunning panoramic views of the city. Visitors can take an elevator to the top and marvel at the breathtaking scenery of the Seine River, the Louvre Museum, and the Notre-Dame Cathedral. The Eiffel Tower's intricate iron lattice structure has remained an architectural marvel since its completion in 1889 and continues to be a symbol of both Paris and France.",
 'In the city of New York, nestled between the towering skyscrapers, lies Central Park, a sprawling oasis of greenery and tranquility. The park, known for its enchanting landscapes and iconic landmarks such as Belvedere Castle and Bow Bridge, attracts visitors from all around the world. On a sunny day, you might see families having picnics near Bethesda Terrace, while runners and cyclists whiz past on the scenic paths. The sounds of the Bronx Zoo and the Metropolitan Museum of Art in the background add to the allure of this vibrant urban getaway.',
 "In the heart of New York City, nestled between towering buildings and bustling crowds, lies Central Park. This iconic green oasis, spanning 843 acres, offers a peaceful retreat from the urban chaos. Visitors can stroll along the pathways, surrounded by enchanting foliage and picturesque lakes. The park is also home to famous landmarks like the Bethesda Terrace, the Central Park Zoo, and the Belvedere Castle, attracting millions of tourists each year. Whether you're seeking a peaceful picnic spot or an adventure-filled day of cycling and horseback riding, Central Park has something for everyone.",
 'In the heart of Paris, the Eiffel Tower stood tall, overlooking the bustling Champs-Élysées. Tourists from around the world flocked to this iconic symbol of France, capturing breathtaking photos of the Seine River and the Louvre Museum in the background. The aroma of fresh croissants filled the air as visitors explored the graceful streets of Montmartre, known for its artistic charm and the famous Sacré-Cœur Basilica.',
 'The Eiffel Tower, located in Paris, France, is an iconic landmark that attracts millions of tourists every year. The Great Barrier Reef, off the coast of Australia, is the largest coral reef system in the world. The Amazon Rainforest, spanning across several countries in South America, is home to a wide variety of plant and animal species. The Taj Mahal, situated in Agra, India, is a breathtaking mausoleum recognized as a UNESCO World Heritage Site. The Nile River, flowing through multiple countries in Africa, is the longest river in the world. The Statue of Liberty, standing proudly in New York Harbor, represents freedom and enlightenment. Mount Everest, located in the Himalayas, is the highest peak on Earth. The Great Wall of China, stretching over thousands of miles, is one of the most impressive architectural marvels in human history. The Sahara Desert, covering a vast expanse of North Africa, is the largest hot desert in the world. The Sydney Opera House, perched on the shores of Sydney, Australia, is a renowned performing arts venue known for its distinctive design.',
 "The mighty Amazon River winds its way through the lush jungles of South America, carrying its waters towards the vast Atlantic Ocean. On its journey, it passes through the sprawling city of Manaus, a bustling metropolis in the heart of Brazil's Amazonas state. The river's mighty presence shapes the lives of countless communities that rely on its waters for fishing, transportation, and irrigation. In the distance, the magnificent Andes Mountains rise majestically, creating a breathtaking backdrop to this magnificent natural wonder.",
 "In the sprawling city of New York, nestled between the towering skyscrapers of Manhattan, lies Central Park, a lush oasis of greenery. The iconic Statue of Liberty stands tall in the distance, overlooking the bustling harbor. Meanwhile, in the heart of Silicon Valley, tech giants like Apple and Google are revolutionizing the world with their cutting-edge innovations. In the world of sports, the legendary Wembley Stadium in London hosts thrilling football matches, while the roaring engines at the Circuit of The Americas in Austin evoke excitement during high-speed races. Whether it's exploring the historic ruins of Machu Picchu in Peru or marveling at the Taj Mahal in India, the world is filled with captivating landmarks and destinations.",
 "In the sprawling city of New York, nestled between towering skyscrapers, you'll find Central Park, a lush oasis of greenery frequented by locals and tourists alike. Across the Atlantic, in the romantic city of Paris, the Eiffel Tower stands tall, overlooking the River Seine, captivating visitors with its magnificent iron lattice structure. In the ancient city of Rome, history unfolds with every step as you wander through the Colosseum, imagining the gladiator battles that once took place within its stone walls. Meanwhile, at the foot of Mount Fuji in Japan, the serene Lake Kawaguchi offers breathtaking views of the snow-capped peak, inviting nature enthusiasts to explore its tranquil surroundings.",
 '\n\nThe Great Wall of China, Grand Canyon, Taj Mahal, Golden Gate Bridge.',
 '\n\nThe Royals took on the Tigers at Kauffman Stadium in Kansas City.',
 "\n\nThe Grand Canyon, Yellowstone National Park, and Sequoia National Park are all breathtaking examples of America's natural beauty.",
 '\n\nThe Hudson River Valley provided breathtaking views of the Catskill Mountains and beautiful sunsets on the Adirondack Lake.',
 '\n\nThe Isle of Wight Ferry sailed into Portsmouth Harbour and disembarked its passengers at Gunwharf Quays. Meanwhile, the Edinburgh Castle loomed in the distance, surrounded by the picturesque cityscape of Edinburgh.',
 '\n\nThe Golden Gate Bridge crossed the San Francisco Bay and connected the cities of Marin County and San Francisco.',
 '\n\nThe Grand Canyon, Taj Mahal, and Great Barrier Reef are all revered natural wonders of the world.',
 '\n\nThe Miami Heat have advanced to the NBA Finals after defeating the Toronto Raptors in Game 5 of the Eastern Conference Finals. The Los Angeles Lakers await in the Finals to determine the 2020 NBA Champion.',
    "The sun shone brightly on the small town, glinting off the cobblestone roads. Everyone was bustling along, going about their daily activities. In the market, vendors hawked their wares to passersby. Music could be heard coming from a nearby cafe, and the smell of freshly baked bread filled the air. A gentle breeze blew in from the sea, bringing with it a hint of salt and the promise of an adventure. All was peaceful and delightful, until a loud crash.",
    "The sun had just set and the entire landscape was in darkness. A solitary figure ventured out of a thick forest, their way lit only by a faint moonlight. As they traveled, an unearthly sound echoed throughout the darkness; a sorrowful and haunting tune. \n\nThe figure moved swiftly, trying to reach their destination before the dawn awoke. Unseen forces seemed to be drawing closer, but the figure plugged on, steady and determined. When the sun began to rise, the figure had made their way through most of the journey and was close to arriving.", "The individual in question has entered the country without proper documentation. Despite efforts to obtain such documentation, it has not been acquired. He poses no threat to public safety and, as such, his request for residency should be considered.",'It was a typical day in late May at Johnson Industries. The employees were hard at work as the company prepared for an upcoming event on June 6th. Suddenly, the alarms started blaring and the sprinkler system was activated. Everyone quickly fled to the safety of the nearby Cybercyte Mall. As they filed in, people noticed a strange sign posted in the lobby containing the message, "Breaking News: Johnson Industries\' latest technology will be unveiled at the event on June',
 'It was April 18th and Lexus had just opened its new dealership in Cornell. People from all over the area had come to take a look at the sleek new cars, as well as test drive them. The lines at the dealership were lengthy but they moved quickly, and a few lucky people were able to get a behind-the-scenes tour of the showroom. Many of them commented on how modern and well stocked the dealership was. The sales staff',
    ' It was the 15th of August, a day which the employees of Caterx Corporation were eagerly anticipating. This day marked the launch of their newest project, the Applewood Mall expansion, which would add an additional 82,000 square feet to the facility.The team of engineers had worked long and hard to develop the ideal way to expand the mall, a process which included multiple scenario planning sessions and site visits to multiple other centers of comparable size. The goal had always been to',
 'It was a warm day on February 8th. Apple Inc. and Samsung had been working together for months, collaborating on a project that would revolutionize technology. The two companies had set up a meeting in Google’s headquarters in Silicon Valley, where they hoped to discuss the progress they had achieved. When they arrived at the meeting, the executives from both companies were filled with hope and enthusiasm. The atmosphere was electric with ideas, and they were confident that this meeting would',
 'March 14th, 2006, Johnson & Clarke Company had its computer system crash. It caused disruption to its services and meant employees had to work additional hours to try to get their systems back up and running. For days, the team worked diligently to repair the damage and eventually got everything back in working order. The company held a small celebration at McDonalds, to show appreciation for all the hard work their employees had done to put things back together. After a day of delicious meals and fun activities',
 " It was a beautiful summer day on June 4th, and Macy's department store was bustling with shoppers.",
 ' Walmart had an exciting day on December 22, 2020. Out of the blue, Amazon had asked them to open a new store in a different city across the country. Walmart, never one to turn down an opportunity, quickly accepted. By mid-February, they were well on their way to opening the new store in San Francisco. Construction went smoothly and by August, the new store was ready to open its doors. Walmart put out a press release announcing the grand opening',
 'The night was February 14th, and Starbucks and Burger King were bustling with couples and friends celebrating the night of love.',
 'It was June 4th, 2019 and the city of Franklin was abuzz with excitement. The day had been marked in everyone\'s calendars for months; it was the opening of the first Amazon store in town. The store had been highly debated in the city council, but the positives far outweighed the negatives in public opinion.',
 'Once upon a time, Microsoft had launched a revolutionary new product that they hoped would extend their market dominance. On July 20th, 2021 the company sent representatives to Starbucks to deliver a demonstration of the product to a select group of potential customers. All who attended the event were amazed by the cutting-edge technology that the product offered - this was sure to be the next big platform revolution. The Microsoft executives left the Starbucks with a standing ovation, and a few of the potential',
 'It was June 19th, the start of the summer season and the excitement in the air was palpable. Everyone was visiting the Walmart downtown, stocking up supplies for their upcoming vacations. Everyone was in good spirits, taking their time while selecting their items. Just as the line seemed to be getting shorter, something unexpected happened. An announcement came over the intercom: all of the Hewlett Packard computers in the electronics department had been discounted by 50%. Curious shoppers hurriedly packed',
 'McDonalds and Burger King had been arch rivals for many years. On August 13th, the two companies decided to collaborate and open the first ever hybrid restaurant. The location was chosen to be in the heart of downtown Washington DC. Ambient lighting, a wide selection of menu items, and comfortable seating made the restaurant an inviting place. At the grand opening, both companies held a ribbon cutting ceremony. It was attended by the mayor, business owners, and local citizens. Everyone',
 'Once upon a time, in the city of San Francisco, there was a major event planned for the summer of 2020. Johnson Financial Group had agreed to sponsor this event, and as part of the agreement there was a large exhibit from the Apple Store that was set up in a nearby park. The exhibit included the latest advancements in technology, and it was expected to draw in a large crowd.On the day of the event, the park was filled with people from all over the state',
 ' It was a chilly December 12th in Detroit, Michigan as the giant Ford factory churned out its famous cars. After a long and busy day, the workers finally left behind the lush green energy of the factory for the night. At the same time, a large shipment was arriving at the Apple store downtown. Inside the cargo were all of the newest tech toys and gadgets. As the lights in the store flickered, setting a festive mood, the familiar tune of',
 "It was February 14th, and McDonalds was hosting a special Valentine’s dinner in their restaurant. For the evening, the staff had arranged a festive atmosphere, with decorations and flowers. The dinner was a success, with plenty of guests enjoying the five-course menu. The highlight of the evening was when everyone indulged in a delicious chocolate fondue made with Hershey's chocolate. Smiles were all around as couples celebrated their love for one another. With that, the magical" ]
    return spans

def dobs():
    birthdays = dates_of_birth = [
    "10/9/2001","January 4, 1930","5th of June, 1975","12-25-1998",
    "March 14th, 1987","8/17/1963","February 29, 1992","7/21/1979",
    "October 12, 1968","6th June 1995","11-1-1950","April 2nd, 1945",
    "9/30/1984","May 25, 1971","2/14/1923","July 7th, 1969","3-20-2002",
    "November 15, 1956","4/18/1972","September 9, 1982","12th of December, 1935",
    "1/8/1966","August 23, 1978","2/10/1999","June 1st, 1960","10-31-1947",
    "January 19, 1991","7/6/1983","October 3, 1976","8th May 1954","9-14-1967",
    "July 29, 1989","5/15/1940","December 6, 1974","March 21st, 1980","11/28/1962",
    "February 17, 1998", "6/22/1938", "November 8, 1953","4th of April, 1964",
    "2/4/1996","June 11, 1977","1-1-1932","September 5, 1949","7/12/1985",
    "August 27, 1971","3/25/1994","May 9th, 1963","10-20-1987","April 30, 1958",
    "9/26/1969","October 16, 1981","12/8/1942","February 2nd, 1967",
    "8-11-1973","January 7, 1950","7/3/1992","July 16, 1986","4/28/1937",
    "March 12, 1978","11th of November, 1965","3/19/1995","June 23, 1959",
    "1-15-1990","September 1, 1948","9/10/1980","August 4, 1972",
    "2/27/1961","May 8th, 1985","10-6-1977","February 21, 1968",
    "7/14/1944","December 1, 1955","5/5/1966","October 25, 1989",
    "4th of July, 1936","1/13/1979","March 30, 1962","11-22-1983",
    "September 17, 1970","8/9/1941","November 26, 1964","6/5/1997",
    "April 19, 1957","12-10-1971","January 31, 1988","7/29/1952",
    "July 18th, 1974","2/6/1969","June 27, 1984","10th of October, 1960",
    "3/7/1993","August 13, 1951","5/3/1975","November 4, 1986",
    "9-23-1968","February 8, 1997","8/21/1943","December 14, 1958","6/15/1972",
    "The fifteenth day of March, in the year 1990", "The twenty-seventh day of September, in the year 1985",
    "The fourth day of December, in the year 2001", "The nineteenth day of June, in the year 1978",
    "The eighth day of April, in the year 1995", "The eleventh day of August, in the year 1982",
    "The twenty-fifth day of January, in the year 2000", "The seventh day of July, in the year 1992",
    "The thirteenth day of October, in the year 1989", "The thirtieth day of May, in the year 1976",
    "The twenty-second day of November, in the year 1988", "The fourteenth day of February, in the year 1997",
    "The eighth day of September, in the year 1980","The third day of March, in the year 1993",
    "The seventeenth day of June, in the year 1979","The twenty-ninth day of October, in the year 2005",
    "The twelfth day of December, in the year 1987","The twenty-first day of April, in the year 1998",
    "The second day of August, in the year 1984","The ninth day of February, in the year 1996",
    "The thirtieth day of May, in the year 1976","The first day of July, in the year 1991",
    "The seventh day of November, in the year 1977","The eighteenth day of January, in the year 2002",
    "The sixth day of May, in the year 1986","The fourteenth day of July, in the year 1994",
    "The fifth day of October, in the year 1983","The thirtieth day of December, in the year 1999",
    "The fourth day of April, in the year 1975","The ninth day of March, in the year 2004",
    "On March 15, in the memorable year 1990", "Celebrating a birthday on March 4th, way back in 1982",
    "In the year 1976, on the glorious day of April 30", "On January 6, amid the snowfall of 1993",
    "Amidst the autumn leaves of October 17, in the magical year 1987", "August 12, when the sun was high, in 2001",
    "On December 8, when the world was different, in 1995", "On the third day of November, amidst the falling leaves of 1988",
    "June 29, when the flowers bloomed in 1979", "September 20, in the season of change, in 1980",
    "Amidst the blossoming spring of April 19, in 1998", "On the 26th of July, under the starry night of 1992",
    "May 18, when the world was in bloom, in 1983", "In 1996, on a crisp February 9, a year to remember",
    "November 22, as the world turned, in 1994", "Amidst the blooming flowers of May 7, in 1981",
    "On a warm June 14, in the year 1997", "February 2, when the world was quiet, in 2005",
    "On the fifteenth day of August, in the vibrant year 1993", "In the midst of winter on January 29, in 1986",
    "March 25, during the season of renewal, in 1977", "On October 9, as the leaves fell, in 1998",
    "Amidst the golden hues of September 12, in 1984", "The twenty-first day of November, in the year 1999",
    "On April 3, when the world was reborn, in 1989", "In the year 2000, on July 19, under the blazing sun",
    "May 13, surrounded by spring's beauty, in 1982", "On a cool December 17, in the year 1994",
    "February 28, under the stars, in 1978", "Amidst the falling snow on December 5, in 1992",
    "On April 15, as the world woke up, in 2001", "The fourth day of July, in the year 1985",
    "In the midst of autumn on November 1, in 1990", "On August 22, when the world was different, in 1987",
    "The seventh day of September, in the memorable year 1979","September 10, 1992",
    "May 3, 1984","On December 1, in the year 1977","July 27, 1995","In 2000, on April 9",
    "August 6, 1988","The twenty-third day of June, in the year 1999",
    "February 12, 1981","April 5, 1996","In the year 1975, on March 19",
    "June 26, 1990","On January 14, in the memorable year 1983","March 28, 1994",
    "May 8, 1986","On November 10, in 1989","In 1997, on October 31",
    "The fifth day of July, in the year 1978","December 22, 2003",
    "August 17, 1991","On February 25, in 1998","The tenth day of September, in the year 1985",
    "January 2, 2002","On May 21, in 1976","July 15, 1993","September 8, 1982",
    "In 1987, on March 7","November 24, 1990","On April 11, in 1995",
    "June 18, 1979","The fifteenth day of August, in the year 1984",
    "February 8, 2004","On December 16, in 1981","October 19, 1989",
    "In 2001, on July 13","April 3, 1987","May 2, 1996",
    "On June 12, in the memorable year 1978","August 31, 1993",
    "The twenty-sixth day of January, in 1992","March 29, 1986",
    "In 1980, on November 5","July 24, 1999",
    "On September 29, in 1983","October 14, 1995",
    "The eleventh day of February, in the year 1988","December 4, 1991",
    "On May 16, 1977","In 2002, on April 20","June 7, 1985",
    "July 3, 1994","9/10/95","2-3-84", "11/15/76","07-27-03",
    "6/9/88","23,33,1949","4--02--004","5/15/90",
    "1-29-79","6-26-99","12/12/86","8--6--1978",
    "10-31-97","5/5/80","22,17,2001","28--7--1995","4-11-91",
    "8/31/77","2-25-98","9-10-85", "June 1998","8/2007",
    "4--1996","November","5-22","July 1980","12/2015",
    "9--15","January","2-2012","August 1993","10/1999",
    "7--2003","April","6-1977","May 1986","11/2000",
    "3--2008","December","1-1989","September 1992","2/2004", "8--2014",
    "October","9-1985", "March 1991", "5/2001", "4--2018","February",
    "7-1997", "1929", "2012", " 1994", " 1937", "1956 "
    ]
    
    return birthdays
